### ISSUE TITLE
New Changes to Push Certificates — Action Needed?

### ISSUE THREAD

**Issue by coneybeare** [PRX/apn_on_rails#15]
Apple has been sent out this email which describes changes to the certificates.  Do we need to regenerate our certificates in the app?
# 

Important changes to Apple Push Notification certificates

Dear Developer,
On December 22, 2010, the production Apple Push Notification service will begin to use a 2048-bit TLS/SSL certificate that provides a more secure connection between your provider server and the Apple Push Notification service.

To ensure you can continue to validate your server's connection to the Apple Push Notification service, you will need to update your push notification server with a copy of the 2048-bit root certificate from Entrust's website. This will not require a change to your iOS apps -- this update only applies to provider servers.

If you have been successfully validating the certificate chain in the APNs sandbox environment, you already have the root certificate you need. Simply install the same 
root certificate on your production push provider servers.

More details on validating your provider communication channel can be found in the Provider Communication with Apple Push Notification service section of the Local and Push Notification Programming Guide.
#

**Comment by mihael** [comment]
I think not. If I remember correctly the certificates I created where already 2048-bit.

**Comment by Jirapong** [comment]
I'm getting this error can't push message SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate revoked

**Comment by mihael** [comment]
Here is a more in depth explanation http://www.24100.net/2010/12/latest-apple-push-notification-certificate-changes-decrypted/

**Comment by Jirapong** [comment]
It turn out to be my wrong certificate. issue resolved. Thank you very much.

**Comment by rebeccanesson** [comment]
As Mihael says, as long as your certificates are valid, no changes are required in the app.
