### ISSUE TITLE
Child properties of the alert property

### ISSUE THREAD

**Issue by mguren** [PRX/apn_on_rails#17]
I don't see a way to add an alert dictionary in order to push a launch-image.  When I add the following:  {:question_id=>1234, :alert=>{"launch-image"=>"Default-AnswerReady.png"}}

APN is creating {:question_id => 1234, :alert => "launch-imageDefault-AnswerReady.png}

**Comment by rebeccanesson** [comment]
The alert field is just for the text of the message that is displayed to the user and only stores a string.  

If you want to include some custom fields, check out the custom_properties attribute.
