### ISSUE TITLE
Apn_on_rails uses deprecated globals RAILS_ENV and RAILS_ROOT

### ISSUE THREAD

**Issue by rsellberg** [PRX/apn_on_rails#18]
Should be Rails.env and Rails.root.to_s respectively, in order to be Rails3 kosher.

**Comment by rebeccanesson** [comment]
apn_on_rails is not yet Rails 3 compatible.  We're looking into whether to try to make a single gem that works both for Rails 3 and Rails 2 or whether it will be two separate versions.
