### ISSUE TITLE
rake aborted! invalid DER-encoded certificate data

### ISSUE THREAD

**Issue by bhushangahire** [PRX/apn_on_rails#21]
I have followed all the steps for converting the Certificate but I am getting the 

rake aborted!
invalid DER-encoded certificate data

Error all the time ...

Let me know what I am missing here...

Thanks
Bhushan Ahire

**Comment by rebeccanesson** [comment]
It sounds like you haven't got the certificate encoding quite right yet.  Without more information on what you are doing it is hard to guess what is going wrong.
