### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by breiko83** [PRX/apn_on_rails#32]
Hello,
I'm getting this error while I'm trying to send push notifications to about 100 devices.

RAILS_ENV="production" rake apn:notifications:deliver
(in /home/breiko/public_html/iosmanager)
Broken pipe

What does this mean?

**Comment by Jirapong** [comment]
I have same issue, it looks like more devices caused error to the plugin.

**Comment by rnaud** [comment]
Having the issue also, has any one been looking at it ? :/

**Comment by ramigg** [comment]
I made a fix for that. I send now to a few thousands with no problem. I also did a fix to feedback.

https://github.com/ramigg/apn_on_rails

**Comment by breiko83** [comment]
Wow! Thank you very much, I will try asap and check if it solves the issue!

**Comment by breiko83** [comment]
With your fix it works like a charm now! Thank you!!
