### ISSUE TITLE
Group notification example

### ISSUE THREAD

**Issue by amithooda** [PRX/apn_on_rails#35]
heyy 
can u provide a group notification example??
and if it is necessary to hav the token of the all devices to which group notification is to be send??

Regards,
Amit Hooda

**Comment by ramigg** [comment]
```
group = APN::Group.find_by_name('my_group')
APN::GroupNotification.create(:group => group, :badge => 12) # can add also sound, alert etc.
APN::App.send_group_notifications
APN::App.process_devices # Feedback - This is necessary to delete invalid devices
```

**Comment by amithooda** [comment]
thnks i was able to send it earlier,,,, but thanks 4 the last step i wasnt knwing that :) ,,,,

**Comment by hardgolf** [comment]
I am having a problem regarding the group notification. I was able to send it before but now the code line APN::App.process_devices cannot find devices that I want to send
