### ISSUE TITLE
Rails 3.2 and self.table_name

### ISSUE THREAD

**Issue by mjankowski** [PRX/apn_on_rails#38]
I'm not sure if this changed in 3.2 or I have something else interfering, but while trying to upgrade to 3.2.1, I see some test failures with something like "apn_bases does not exist" - and my guess is that the `def self.table_name` in APN base.rb used to return things like apn_devices, and now returns apn_bases incorrectly.

**Comment by kookster** [comment]
Thanks for logging this issue.

My guess is the super class needs to be marked as an abstract:

self.abstract_class = true

I'll try it out and put that in.

It also should not be trying to test an instance of that class, only the children, as it should be, uh abstract - that's the point.

**Comment by kookster** [comment]
yeah, the abstract thing was the issue.  I have checked in the fix, if you get master this will work, and I'll release a gem update presently.

I am looking at some of the failing specs now, but they are in older specs I didn't write, so may take me awhile to get them all working.

**Comment by mjankowski** [comment]
Awesome, thanks.

**Comment by coneybeare** [comment]
This fix is confirmed.
