### ISSUE TITLE
rake apn:feedback:process still requires apn_apps

### ISSUE THREAD

**Issue by russellquinn** [PRX/apn_on_rails#9]
Mysql::Error: Table 'development_database.apn_apps' doesn't exist: SHOW FIELDS FROM `apn_apps`

**Comment by rebeccanesson** [comment]
Hi Russell, 

You do need to run the migrations and have an apn_apps table in your database.  You do not have to create any APN::App instances, however.  The table should be created for you if you generate and run the migrations included with the gem.  

Let me know if I'm misunderstanding your issue. 
Thanks, 
Rebecca

**Comment by russellquinn** [comment]
Aha, OK. In that case, it's fine. I thought the latest version was supposed to run without the table existing even, but I understand now.

Thanks for clearing that up.
